Import('env')

local = env.Clone()

local.Append(CPPPATH=['include/'])
local.Append(LIBPATH=['lib/'])
local.Append(LIBS=['enet'])

final = local.Program(target='bin/client', source=['src/client.cpp'])

Return('final')
